"""table

Revision ID: 008a8087cb9d
Revises: 40f627546b84
Create Date: 2024-02-23 21:00:54.104011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008a8087cb9d'
down_revision = '40f627546b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###
